typography_spectrum: 0.27579541839779087
content_rating:
  adult: false
color:
  brandStrength: 0.23528246387931528
  lightness: 0.1480662574964843
  saturation: 0.7923070585033349
  rhythmicContrast: 0.8909640683996316
  brandColors:
    - '#B9121B'
    - '#4C1B1B'
    - '#F6E497'
    - '#FCFAE1'
    - '#BD8D46'
github: true
layout_spectrum: 0.15468982617361562
author:
  name: Spethe 2016
  email: ''
  url: ''
logo: null
name: Spethe
url: 'http://spethe.com'
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/5e693350-1a60-454b-b2e7-7bbe5ba7418d.jpg
title: >-
  Hand-picked content on Accessibility & Assistive Technologies from across
  world
content: []
description: >-
  Enabling people with disabilities, elderly & the community with curated
  content
purpose:
  - type: contact
    url: 'mailto:spethe.network@gmail.com'
    label: Email us to learn more!
  - type: contact
    url: 'mailto:blessinvarkey@gmail.com'
    label: Write for us
