typography_spectrum: 0.2619848186310639
content_rating:
  adult: false
color:
  brandStrength: 0.22033872359948656
  lightness: 0.7578325502638991
  saturation: 0.4098477723653253
  rhythmicContrast: 0.9891970539767073
  brandColors:
    - '#2E0927'
    - '#D90000'
    - '#FF2D00'
    - '#FF8C00'
    - '#04756F'
github: true
layout_spectrum: 0.4344212548458709
author:
  name: Spethe 2016
  email: ''
  url: ''
logo: null
name: Spethe
url: 'http://spethe.com'
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/5e693350-1a60-454b-b2e7-7bbe5ba7418d.jpg
title: Hand-picked content from people & professionals across world
content: []
description: >-
  Enabling people with disabilities, elderly & the community with curated
  content
purpose:
  - type: contact
    url: 'mailto:spethe.network@gmail.com'
    label: Email us to learn more!
  - type: contact
    url: 'mailto:blessinvarkey@gmail.com'
    label: Write for us
