typography_spectrum: 0.6293705013606439
color:
  brandStrength: 0.9791572872335368
  lightness: 0.8786977118418764
  saturation: 0.9329114061819003
  rhythmicContrast: 0.730318698762538
  brandColors:
    - '#2E0927'
    - '#D90000'
    - '#FF2D00'
    - '#FF8C00'
    - '#04756F'
github: true
layout_spectrum: 0.06756640510522935
author:
  name: Blessin Varkey
  email: blessinvarkey@gmail.com
  url: www.spethe.com
logo: null
name: Spethe
navigation:
  - name: Lifestyle
    url: 'http://www.stories.spethe.com/category/lifestyle/'
    type: external
  - name: Research
    url: 'http://www.stories.spethe.com/category/research/'
    type: external
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/5e693350-1a60-454b-b2e7-7bbe5ba7418d.jpg
title: Hand-picked disability content from people & professionals across world
content: []
description: ''
purpose:
  - type: contact
    url: 'mailto:spethe.network@gmail.com'
    label: Email us to learn more!
  - type: contact
    url: 'mailto:blessinvarkey@gmail.com'
    label: Write for us
