layout_spectrum: 0.9581480405233468
typography_spectrum: 0.270583389983743
color:
  brandStrength: 0.23023549146221786
  lightness: 0.14135802006404294
  saturation: 0.7908005153198755
  rhythmicContrast: 0.8909646835082239
  brandColors:
    - '#B9121B'
    - '#4C1B1B'
    - '#F6E497'
    - '#FCFAE1'
    - '#BD8D46'
content_rating:
  adult: false
github: true
author:
  name: Spethe 2016
  email: ''
  url: ''
logo: null
name: Spethe
url: 'http://spethe.com'
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/5e693350-1a60-454b-b2e7-7bbe5ba7418d.jpg
title: >-
  Hand-picked content on Accessibility & Assistive Technologies from across the
  world
content: []
description: >-
  Enabling people with disabilities, elderly & the community with curated
  content
purpose:
  - type: contact
    url: 'mailto:spethe.network@gmail.com'
    label: Email us to learn more!
  - type: contact
    url: 'mailto:blessinvarkey@gmail.com'
    label: Write for us
