typography_spectrum: 0.7191158660027281
color:
  brandStrength: 0.4151222050050734
  lightness: 0.6439998128673634
  saturation: 0.8759016188491358
  rhythmicContrast: 0.0833405763373738
  brandColors:
    - '#000000'
    - '#263248'
    - '#7E8AA2'
    - '#FFFFFF'
    - '#FF9800'
github: true
layout_spectrum: 0.2758009746290817
logo: null
name: Spethe
navigation:
  - name: Lifestyle
    url: 'http://www.stories.spethe.com/category/lifestyle/'
    type: external
  - name: Research
    url: 'http://www.stories.spethe.com/category/research/'
    type: external
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/5e693350-1a60-454b-b2e7-7bbe5ba7418d.jpg
title: Spethe
content: []
description: ''
purpose:
  - type: contact
    url: 'mailto:spethe.network@gmail.com'
    label: Email us to learn more!
  - type: contact
    url: 'mailto:blessinvarkey@gmail.com'
    label: Write for us
